name: Release
on:
  create:
    tags:
    - v*

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: yarn
    - run: yarn build
    - name: Upload release
      uses: yakuhzi/action-release@v1
      with:
        file: dist/main.js
        changelog: dist/manifest.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}